### ISSUE TITLE
Challenge 268 duplication.

### ISSUE THREAD

**Issue by Ouss4** [FreddieV4/DailyProgrammerChallenges#156]
Why hard challenge 268 is in the base directory and in the Hard Challenges directory?

**Comment by freddiev4** [comment]
Looks like there was no `[Hard]` challenge for the week after challenge 268, so it got pulled twice, because `post-challenges.py` pulls the three newest challenges, but that's making the assumption that there are three new challenges each week (easy/intermediate/hard)

<img width="828" alt="screen shot 2016-06-15 at 1 59 30 pm" src="https://cloud.githubusercontent.com/assets/8339018/16091404/799e24c0-3301-11e6-829b-5fe0ede53e71.png">

Will fix this sometime soon.
